format = """
[](fg:#050396)\
$username\
[](bg:#3483eb fg:#050396)\
$directory\
[](fg:#3483eb bg:#244999)\
$git_branch\
$git_status\
[](fg:#244999 bg:#33658A)\
$c\
$golang\
$java\
$nodejs\
$rust\
[](fg:#33658A bg:#25501c)\
$cmd_duration\
[](fg:#25501c)
[](fg:#050396)\
[$character](bg:#050396)\
[](fg:#050396 bg:#3483eb)\
[](fg:#3483eb bg:#244999)\
[ ](fg:#244999)
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#050396"
style_root = "bg:#050396"
format = '[ $user ]($style)'


[fill]
disabled = true

[line_break]
disabled = true

[directory]
style = "bg:#3483eb"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#33658A"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#33658A"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
style = "bg:#244999"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#244999"
format = '[$all_status$ahead_behind]($style)'
conflicted = "= "
ahead = "⇡ "
behind = "⇣ "
diverged = "⇕ "
up_to_date = ""
untracked = "? "
stashed = "$ "
modified = "! "
staged = "+ "
renamed = "» "
deleted = "✘ "

[golang]
symbol = " "
style = "bg:#33658A"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#33658A"
format = '[ $symbol ($version) ]($style)'

[rust]
style = "bg:#33658A"
symbol = ""
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#25501c"
format = '[ $time]($style)'

[cmd_duration]
min_time = 500
style = "bg:#25501c"
format = '[ $duration]($style)'

[character]
format = " $symbol"
success_symbol = "[👍](bg:#050396)"
error_symbol = "[👎](bg:#050396)"
