theme = "catppuccin_mocha"

###############################################################################################
# EDITOR
###############################################################################################
[editor]
# line-number = "relative"
true-color = true
cursorline = true
color-modes = true
bufferline = "multiple"
scrolloff = 10
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
end-of-line-diagnostics = "hint"
# rulers = [80]
 
[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

# [editor.whitespace]
# render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.lsp]
display-messages = true
# display-signature-help-docs = false
# auto-signature-help = false

[editor.statusline]
left = [
"mode",
"spacer",
"version-control",
"spacer",
"separator",
"file-name",
"file-modification-indicator"
]
right = [
"spinner",
"spacer",
"workspace-diagnostics",
"separator",
"spacer",
"diagnostics",
"position",
"primary-selection-length",
"file-encoding",
"file-line-ending",
"file-type"
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
character = "|"
skip-levels = 1

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0

##############################################################################################3
# KEYs
##############################################################################################3

[keys.insert]
C-c = "toggle_comments"
C-space = "completion"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.select]
C-c = "toggle_comments"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
X = ["extend_line_up", "extend_to_line_bounds"]
ret = "goto_word"

[keys.normal]
a = ["append_mode", "collapse_selection"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
esc = ["collapse_selection", "keep_primary_selection"]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"
X = ["extend_line_up", "extend_to_line_bounds"]
ret = "goto_word"

[keys.normal.space.c]
r = [":w", ":config-reload"]
o = ":config-open"
l = ":o ~/.config/helix/languages.toml"

[keys.normal.space.o]
g = ":sh zellij run -fc --height 100% --width 100% -x 0 -y 0 -- lazygit"
f = ":sh zellij run -fc -- yazi"
m = ":sh zellij run -fc -- glow -p ./README.md"
r = ":set whitespace.render none"
w = ":set whitespace.render all"

[keys.normal.space.a]
g =[":sh go mod tidy", ":reload-all", ":lsp-restart"]
r = [":reload-all", ":lsp-restart"]
l = ":sh zellij run -d right -- revive -formatter stylish ./..."

[keys.normal.space]
W = ":write"

